#!/usr/bin/env bash
echo "==list objects"

# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# aws s3api list-bucket-v2 --bucket my-example-bucket-ab --region eu-west-1
aws s3api list-bucket-v2 \
--bucket $list_NAME \
--list-bucket-configuration="LocationConstraint=eu-west-2" \
--query Location \
--output text